### ISSUE TITLE
Orz, 给大佬跪了

### ISSUE THREAD

**Issue by Finn-Fengming** [Patrickctyyx/patrickctyyx.github.io#1]
dalao写博客直接用的html写的Orz..太强了..

弱弱小声接一句...这样的话不是会拖慢页面加载速度么..(毕竟某些东西重复加载了多次呀)

**Comment by Patrickctyyx** [comment]
不是啊，html是自动生成的啊，加载速度确实是个大问题...不过那些是在不同页面的就没事啦

2016-12-27 17:56 GMT+08:00 Ecohnoch <notifications@github.com>:

**Comment by Finn-Fengming** [comment]
我发现还是不能评价诶....是我打开方式不对吗

**Comment by Patrickctyyx** [comment]
需要注册一个账号？
